#!/bin/bash

GIT="${HOME}/.dotfiles"
DOTFILES=$GIT/files
CONF="${HOME}"
FILES=($(cd $DOTFILES && find . -maxdepth 1 -name '.?*' | cut -c 3-))

function installSymlinks() {

	for i in "${FILES[@]}"; do
		rm -rf ${HOME}/$i
		if ln -s $DOTFILES/$i ${HOME}/$i; then
			echo Link to ${HOME}/$i created!
		fi
	done
}

function gitsubmoduleUpdate() {

	cd $GIT
	git submodule init
	git submodule update
}

function installVimPackages() {
	vim +PluginInstall +qall
}

function installTmuxWithPlugins {

    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        

}
# Need to do in ansible module for centos and ubuntu ( debian ) servers
function installPackages() {

    pkg install vim coreutils wget htop curl zsh fzf ruby 

}

function install() {

	installSymlinks
	installPackages
	gitsubmoduleUpdate
	installVimPackages
    installTmuxWithPlugins
}
case "$1" in

install)
	install
	;;
*)
	echo $"Usage: $0 {install|clean|help|status}"
	exit 1

	;;
esac
